config/routes.rb
ProjectMellon::Application.routes.draw do
  root 'welcome#index'
  resources :games, :players, :linear_regression, :optimization
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player
  default_scope order('game_day DESC')


  def more_than_twenty?
    self.points > 20.0
  end

end

app/models/player.rb
class Player < ActiveRecord::Base

  has_many :games
  attr_reader :teams

  def player_tokens=(ids)
    player_ids = ids.split(",")
  end

  def self.search(search)
    if search
      @players = Player.find(:all, conditions: ['name LIKE ?', "%#{search}%"])
    else
      @players = Player.all
    end
  end

  def teams
    games.pluck(:team).uniq.to_sentence
  end

  def fdp_per_game
    games.pluck(:fanduel_points).sum / games.length
  end

  def fdp_per_36
    begin
      games.collect {|game| (game.fanduel_points / game.minutes) * 36}.sum / games.length
    rescue
      return 0.0
    end
  end

  def minutes_per_game
    games.pluck(:minutes).sum / games.length
  end

  def avg_adj_fdp_per_1k
    if games.pluck(:salary).all?
      games.collect { |game| (game.fanduel_points / game.salary)*1000 }.sum / games.length
    else
      0.0
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def InitR
   RSRuby.instance
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    unless params[:sort]
      params[:sort] = "fdp_per_36"
      params[:direction] = "desc"
    end
    @games = Game.order("#{params[:sort]} #{params[:direction]}").select {|sign_up| can? :read, sign_up }.paginate(:page => params[:page])
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:fanduel_points, :game_day, :player_id, :minutes, :rotowire_fdp, :numberfire_fdp, :is_starter, :team, :opponent, :points, :rebounds, :assists, :steals, :blocks, :turnovers)
    end

end

app/controllers/linear_regression_controller.rb
class LinearRegressionController < ApplicationController
  def index

    if params[:x].nil? || params[:y].nil?
      params[:x] = "minutes"
      params[:y] = "fanduel_points"
    end

    @game_data = Game.all.pluck(params[:x], params[:y])
    @x = @game_data.collect {|point| point[0] }
    @y = @game_data.collect {|point| point[1] }

    @col_names = Game.columns.select {|c| c.type==:float}.collect {|c| c.name}.reject! {|c| c.include? "fdp"}
  end
end

app/controllers/optimization_controller.rb
class OptimizationController < ApplicationController
  def show
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    unless params[:sort]
      params[:sort] = "fdp_per_36"
      params[:direction] = "desc"
    end

    #@players = Player.all.sort! { |a,b| a.send(params[:sort]) <=> a.send(params[:sort]) }
    @players = Player.all.paginate(page: params[:page])
    if params[:name]
      player = Player.find_by_name(params[:name])
      redirect_to "/players/#{player.id}"
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/linear_regression_helper.rb
module LinearRegressionHelper
end

app/helpers/optimization_helper.rb
module OptimizationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.slim
= form_for @game do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :player_id
    = f.text_field :player_id
  .field
    = f.label :game_day
    = f.date_select :game_day

  .field
    = f.label :fanduel_points
    = f.text_field :fanduel_points
  .field
    = f.label :minutes
    = f.text_field :minutes
  .field
    = f.label :rotowire_fdp
    = f.text_field :rotowire_fdp
  .field
    = f.label :numberfire_fdp
    = f.text_field :numberfire_fdp
  .actions = f.submit 'Save'

app/views/games/edit.html.slim
h1 Editing game

== render 'form'

= link_to 'Show', @game
'|
= link_to 'Back', games_path

app/views/games/index.html.slim
h1 Listing games

table
  thead
    tr
      th Fanduel points
      th Date
      th
      th
      th

  tbody
    - @games.each do |game|
      tr
        td = game.fanduel_points
        td = game.game_day
        td = link_to 'Show', game
        td = link_to 'Edit', edit_game_path(game)
        td = link_to 'Destroy', game, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Game', new_game_path

app/views/games/new.html.slim
h1 New game

== render 'form'

= link_to 'Back', games_path

app/views/games/show.html.slim
p#notice = notice

p
  strong Fanduel points:
  = @game.fanduel_points
p
  strong Date:
  = @game.game_day

= link_to 'Edit', edit_game_path(@game)
'|
= link_to 'Back', games_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Mellon</title>
  <link rel="icon" href="http://images.wikia.com/nba/images/archive/6/64/20060916025851!Favicon.ico">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<div class="navbar navbar-fixed-top">
<div class="container-fluid">
    <a href="/"><img src="http://i.imgur.com/TtMC2HD.jpg" height="50" id="pm-logo"></a>

  <span id="the-basics">
    <input class="typeahead input-lg" type="text" placeholder="Search (e.g. LeBron)"></input>
  </span>



&nbsp;

</div>
</div>
<br><br><br>
<%= yield %>

</body>
<script type="text/javascript">
  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substringRegex;

      // an array that will be populated with substring matches
      matches = [];

      // regex used to determine if a string contains the substring `q`
      substrRegex = new RegExp(q, 'i');

      // iterate through the pool of strings and for any string that
      // contains the substring `q`, add it to the `matches` array
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          // the typeahead jQuery plugin expects suggestions to a
          // JavaScript object, refer to typeahead docs for more info
          matches.push({ value: str });
        }
      });

      cb(matches);
    };
  };

  var players = <%== Player.select('distinct name').collect { |p| p.name } %>;

  $('#the-basics .typeahead').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'players',
    displayKey: 'value',
    source: substringMatcher(players)
  });
  </script>
</html>

app/views/linear_regression/index.html.slim
br
h1 align="center" Linear Regression
br
br
h4 You can choose x and y variables with the dropdowns below.

.well.col-md-4 style="display: flex;"
  select.form-control#x-select
    - @col_names.each do |col_name|
      - unless col_name==params[:x]
        option value="#{col_name}" #{col_name.titleize}
      - else
        option value="#{col_name}" selected="selected" #{col_name.titleize}
  select.form-control#y-select
    - @col_names.each do |col_name|
      - unless col_name==params[:y]
        option value="#{col_name}" #{col_name.titleize}
      - else
        option value="#{col_name}" selected="selected" #{col_name.titleize}
.span.col-md-1 &nbsp;
.col-md-6#scatter-plot

.col-md-6#loading
  img src="http://www.monsterpay.com/images/LoadingBar.gif" width="300"

javascript:
  $(document).ready(function()
    {
      $("#loading").hide();
    });


javascript:
  $(function () {
    inputData = #{@game_data};
    fit1 = ss.linear_regression().data(inputData);
    xMin = ss.min(#{@x});
    xMax = ss.max(#{@x});

    return new Highcharts.Chart({
      chart: {
        renderTo: "scatter-plot"
      },
      title: {
        text: '#{params[:y].titleize} on #{params[:x].titleize}'
        },
        xAxis: {
            title: {
                enabled: true,
                text: '#{params[:x].titleize}'
            },
            startOnTick: true,
            endOnTick: true,
            showLastLabel: true
        },
        yAxis: {
            title: {
                text: '#{params[:y].titleize}'
            }
        },
        tooltip: {
          formatter: function() {
            return round(this.x) + " #{params[:x].titleize}, " + round(this.y) + " #{params[:y].titleize}" ;
          }
        },
        series: [{
          type: "scatter",
          name: "All Games",
          color: 'rgba(119, 152, 191, .5)',
          data: inputData
        },
        {
          type: "line",
          name: "Least Squares Line",
          color: "black",
          data: [[xMin,fit1.line()(xMin)], [xMax,fit1.line()(xMax)]]

        }]
    });
  });

app/views/optimization/index.html.slim
h1 align="center" Fanduel Lineup Optimization
br
br
h4
  |Press the &nbsp;
  img src="http://i.imgur.com/CsWzaNd.png"
  |&nbsp; below to get started

h6 align="center"
  |Click
  a href="http://repl.it/1kB/5" &nbsp;here&nbsp;
  | if you want to open in a separate window
iframe src="http://repl.it/1kB/5" width="100%" height="1000" border="0"

app/views/players/_form.html.slim
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      h2 = "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      ul
        - @player.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/players/actual_vs_roto_vs_fanduel.html.slim
javascript:
  $(function() {
    new Highcharts.Chart({
      chart: {
        renderTo: "games_chart"
      },
      title: {
        text: "Fanduel Points vs Projections"
      },
      xAxis: {
        categories: #{raw @player.games.reverse.collect {|game| game.game_day.strftime('%b %d')}}
      },
      yAxis: {
        title: {
          text: "Fanduel Points"
        }
      },
      tooltip: {
        formatter: function() {
          return this.x + ': ' + this.y
        }
      },
      series: [{
        name: "NumberFire Projection",
        data: #{@player.games.reverse.collect {|game| game.numberfire_fdp}}
      }, {
        name: "Rotowire Projection",
        data: #{@player.games.reverse.collect {|game| game.rotowire_fdp}}
      },{
        name: "Fanduel Points",
        data: #{@player.games.reverse.collect {|game| game.fanduel_points}}
      }],
    })
  });

h1
  =@player.name
p
  = link_to 'Back', players_path, :class=>"btn btn-primary"

div id="games_chart"

table.table.table-hover
  thead
    tr
      th Date
      th FDP
      th Rotowire
      th NumberFire

  tbody
    - @player.games.each do |game|
      tr
        td = link_to game.game_day, game
        td = game.fanduel_points
        td = game.rotowire_fdp
        td = game.numberfire_fdp

app/views/players/edit.html.slim
h1 Editing player

== render 'form'

= link_to 'Show', @player
'|
= link_to 'Back', players_path

app/views/players/index.html.slim
div align="center"
  /= will_paginate @players

table.table.table-hover
  thead
    tr
      th Name
      th Team(s)
      th FDP/36mins
      th FDP/Game
      th Minutes/Game
      th FDP/$1K

  tbody
    - @players.each do |player|
      tr
        td = link_to player.name, player
        td = player.teams
        td = player.fdp_per_36.round(2)
        td = player.fdp_per_game.round(2)
        td = player.minutes_per_game.round(2)
        td = player.avg_adj_fdp_per_1k.round(2)

div align="center"
  /= will_paginate @players

app/views/players/new.html.slim
h1 New player

== render 'form'

input.form-control type="text" id="tokenfield" value="red,green,blue"

= link_to 'Back', players_path

app/views/players/show.html.slim
br

p
  = link_to '< Back', root_path, :class=>"btn btn-primary", :style=>"background-color: white; border-color: #c0d9ef; color: black;"
h1 align="center"
  ="#{@player.name} - #{@player.games.pluck(:team).uniq.to_sentence}"

.btn-group align="center" style="padding: 10px 36%;"
  button.btn.btn-default.stat-selector.active type="button" id="fdp-selector" Fanduel Points
  button.btn.btn-default.stat-selector type="button" id="minutes-selector" Minutes
  button.btn.btn-default.stat-selector type="button" id="fdp-per-36-selector" FDP per 36
  button.btn.btn-default.stat-selector type="button" id="salary-selector" Salary

.well.col-md-4 style="margin: 0 33%;"
  table id="summary" width="100%"
    tr
      td Min.
      td 1st Qu.
      td Median
      td Mean
      td 3rd Qu.
      td Max.
    tr
      td id="min" #
      td id="1st-quart" #
      td id="median" #
      td id="mean" #
      td id="3rd-quart" #
      td id="max" #



.chart id="fanduel-points"
.chart id="minutes"
.chart id="fdp-per-36"
.chart id="salary"



h3 Game Log
table.table.table-hover
  thead
    tr
      th Date
      th Salary
      th FDP
      th Minutes

  tbody
    - @player.games.each do |game|
      tr
        td = link_to "#{game.game_day} - #{game.opponent}", game
        td = "$#{game.salary}"
        td = game.fanduel_points
        td = game.minutes


/render Fanduel Points initially
javascript:
  $(function() {
    renderChart("fanduel-points", "Fanduel Points", #{@player.games.pluck(:fanduel_points).reverse}, #{ raw @player.games.reverse.collect {|game| game.game_day.strftime('%b %d') + ' ' + game.opponent}});
  });

javascript:
  $("div.chart:not(:first)").hide();
  $('.stat-selector').click(function() {
    $(".chart").hide();
  });

  $('#fdp-selector').click(function() {
    $("#fanduel-points").show();
    renderChart("fanduel-points", "Fanduel Points", #{@player.games.pluck(:fanduel_points).reverse}, #{ raw @player.games.reverse.collect {|game| game.game_day.strftime('%b %d') + ' ' + game.opponent}});
  });

  $('#minutes-selector').click(function() {
    $("#fdp-selector").removeClass("active");
    $("#minutes").show();
    renderChart("minutes", "Minutes", #{@player.games.pluck(:minutes).reverse}, #{ raw @player.games.reverse.collect {|game| game.game_day.strftime('%b %d') + ' ' + game.opponent}});
  });

  $('#fdp-per-36-selector').click(function() {
    $("#fdp-selector").removeClass("active");
    $("#fdp-per-36").show();
    renderChart("fdp-per-36", "FDP per 36", #{@player.games.reverse.collect {|game| (game.fanduel_points / game.minutes) * 36}}, #{ raw @player.games.reverse.collect {|game| game.game_day.strftime('%b %d') + ' ' + game.opponent}});
  });

  $('#salary-selector').click(function() {
    $("#fdp-selector").removeClass("active");
    $("#salary").show();
    renderChart("salary", "Salary", #{@player.games.pluck(:salary).reverse}, #{ raw @player.games.reverse.collect {|game| game.game_day.strftime('%b %d') + ' ' + game.opponent}});
  });

app/views/welcome/index.html.slim
br
br
.col-md-12
  /h3
    /|I wrote this code for Project Mellon, which is explained in response to the question asking about what projects I have worked on outside of school/work. I am submitting two code samples for your review. You can check out the complete source in
    a href="https://github.com/mhartman4/project-mellon" &nbsp;the Project Mellon Github repository.
  br
  /li
    /h5
      /|The first is Linear Regression done on NBA player performances in the '13-'14 season. These regressions are calculated on the full set of all games (over 25,000 rows of data) in real-time (not cached) on the client-side, using javascript.
  /li
    /h5 The second is a simplified version of my Lineup Optimization algorithm used to help select my Fanduel lineups.
  /li
    /h5 You can also look at individual fantasy player performances by typing a player's name in the search box above.
hr
.col-md-6 align="center"
  h1 Linear Regression
  a href="/linear_regression"
    img.blegh src="http://i.imgur.com/jAkG910.png" width="80%"
  br
/.col-md-6 align="center"
  /h1 Lineup Optimization
  /a href="/optimization"
    /img.blegh src="http://i.imgur.com/qbnz7vw.png" width="80%"
  /br



br
br
br
br
br
br
br
br